version: "3.8"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile.dev
    args:
      RUBY_VERSION: 3.2.2
      PG_MAJOR: 16
      NODE_VERSION: 20.10.0
      YARN_VERSION: 1.22.20
  env_file:
    - .env
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
    RAILS_ENV: ${RAILS_ENV:-development}
    YARN_CACHE_FOLDER: /app/node_modules/.yarn-cache
  stdin_open: true
  tty: true
  image: ${COMPOSE_PROJECT_NAME}:1.0.0
  # unfortunately Volumes megre via <<:app is not working correctly
  # so all volumes added to most basic template
  volumes:
    - .:/app
    - node_modules:/app/node_modules
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle

x-backend: &backend
  <<: *app
  environment:
    <<: *env
    DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    WEB_CONCURRENCY: 0
  depends_on:
    postgres:
      condition: service_healthy

services:
  runner:
    <<: *backend
    command: /bin/bash

  web:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - 3000:3000

  js:
    <<: *app
    command: yarn build --watch

  css:
    <<: *app
    command: yarn build:css --watch

  postgres:
    image: ankane/pgvector:v0.5.1 # based on PG-15, with pg-vector support
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres:
  bundle:
  node_modules:
  rails_cache:
